INSERT INTO dbfiis.administration (name, cnpj, phone, email) VALUES('BRL TRUST', 0, 0, '');
INSERT INTO dbfiis.administration (name, cnpj, phone, email) VALUES('XP INVESTIMENTOS', 0, 0, '');
INSERT INTO dbfiis.administration (name, cnpj, phone, email) VALUES('RIO BRAVO', 0, 0, '');
INSERT INTO dbfiis.administration (name, cnpj, phone, email) VALUES('BTG PACTUAL', 0, 0, '');
INSERT INTO dbfiis.administration (name, cnpj, phone, email) VALUES('BANCO GENIAL', 0, 0, '');
INSERT INTO dbfiis.administration (name, cnpj, phone, email) VALUES('MAF', 0, 0, '');
INSERT INTO dbfiis.administration (name, cnpj, phone, email) VALUES('VÓRTX', 0, 0, '');
INSERT INTO dbfiis.administration (name, cnpj, phone, email) VALUES('GENIAL INVESTIMENTOS', 0, 0, '');
INSERT INTO dbfiis.administration (name, cnpj, phone, email) VALUES('RJI', 0, 0, '');
INSERT INTO dbfiis.administration (name, cnpj, phone, email) VALUES('OLIVEIRA TRUST', 0, 0, '');
INSERT INTO dbfiis.administration (name, cnpj, phone, email) VALUES('HEDGE INVESTMENTS', 0, 0, '');
INSERT INTO dbfiis.administration (name, cnpj, phone, email) VALUES('REAG', 0, 0, '');
INSERT INTO dbfiis.administration (name, cnpj, phone, email) VALUES('BANCO DAYCOVAL', 0, 0, '');
INSERT INTO dbfiis.administration (name, cnpj, phone, email) VALUES('BB GESTAO DE RECURSOS', 0, 0, '');
INSERT INTO dbfiis.administration (name, cnpj, phone, email) VALUES('BV DTVM', 0, 0, '');
INSERT INTO dbfiis.administration (name, cnpj, phone, email) VALUES('BANCO BRADESCO', 0, 0, '');
INSERT INTO dbfiis.administration (name, cnpj, phone, email) VALUES('INTER DTVM', 0, 0, '');
INSERT INTO dbfiis.administration (name, cnpj, phone, email) VALUES('FRAM Capital', 0, 0, '');
INSERT INTO dbfiis.administration (name, cnpj, phone, email) VALUES('MODAL ASSET', 0, 0, '');
INSERT INTO dbfiis.administration (name, cnpj, phone, email) VALUES('null', 0, 0, '');
INSERT INTO dbfiis.administration (name, cnpj, phone, email) VALUES('TRUSTEE DTVM', 0, 0, '');
INSERT INTO dbfiis.administration (name, cnpj, phone, email) VALUES('CREDIT SUISSE', 0, 0, '');
INSERT INTO dbfiis.administration (name, cnpj, phone, email) VALUES('SINGULARE', 0, 0, '');
INSERT INTO dbfiis.administration (name, cnpj, phone, email) VALUES('ID CORRETORA DE TITULOS E VALORES MOBILIARIOS S.A.', 0, 0, '');
INSERT INTO dbfiis.administration (name, cnpj, phone, email) VALUES('CAIXA ECONOMICA FEDERAL', 0, 0, '');
INSERT INTO dbfiis.administration (name, cnpj, phone, email) VALUES('PLANNER', 0, 0, '');
INSERT INTO dbfiis.administration (name, cnpj, phone, email) VALUES('BNY MELLON', 0, 0, '');
INSERT INTO dbfiis.administration (name, cnpj, phone, email) VALUES('VOTORANTIM ASSET', 0, 0, '');
INSERT INTO dbfiis.administration (name, cnpj, phone, email) VALUES('COINVALORES', 0, 0, '');
INSERT INTO dbfiis.administration (name, cnpj, phone, email) VALUES('BANCO OURINVEST S.A.', 0, 0, '');
INSERT INTO dbfiis.administration (name, cnpj, phone, email) VALUES('BR-CAPITAL', 0, 0, '');
INSERT INTO dbfiis.administration (name, cnpj, phone, email) VALUES('PLANNER CORRETORA', 0, 0, '');
INSERT INTO dbfiis.administration (name, cnpj, phone, email) VALUES('CM CAPITAL MARKETS', 0, 0, '');
INSERT INTO dbfiis.administration (name, cnpj, phone, email) VALUES('TIVIO CAPITAL', 0, 0, '');
INSERT INTO dbfiis.administration (name, cnpj, phone, email) VALUES('SANTANDER CACEIS ', 0, 0, '');
INSERT INTO dbfiis.administration (name, cnpj, phone, email) VALUES('WARREN', 0, 0, '');
INSERT INTO dbfiis.administration (name, cnpj, phone, email) VALUES('INTRAG', 0, 0, '');
INSERT INTO dbfiis.administration (name, cnpj, phone, email) VALUES('BEM DTVM', 0, 0, '');
INSERT INTO dbfiis.administration (name, cnpj, phone, email) VALUES('FINAXIS CORRETORA', 0, 0, '');
INSERT INTO dbfiis.administration (name, cnpj, phone, email) VALUES('BANCO FINAXIS', 0, 0, '');
INSERT INTO dbfiis.administration (name, cnpj, phone, email) VALUES('BANCO J. SAFRA', 0, 0, '');
INSERT INTO dbfiis.administration (name, cnpj, phone, email) VALUES('MÉRITO', 0, 0, '');
INSERT INTO dbfiis.administration (name, cnpj, phone, email) VALUES('APEX', 0, 0, '');
INSERT INTO dbfiis.administration (name, cnpj, phone, email) VALUES('PLURAL', 0, 0, '');
INSERT INTO dbfiis.administration (name, cnpj, phone, email) VALUES('TERRA', 0, 0, '');
INSERT INTO dbfiis.administration (name, cnpj, phone, email) VALUES('S3 CACEIS', 0, 0, '');
INSERT INTO dbfiis.administration (name, cnpj, phone, email) VALUES('BTG PATCUAL', 0, 0, '');
INSERT INTO dbfiis.administration (name, cnpj, phone, email) VALUES('BRB DTVM', 0, 0, '');
INSERT INTO dbfiis.administration (name, cnpj, phone, email) VALUES('SANTANDER SECURITIES', 0, 0, '');
INSERT INTO dbfiis.administration (name, cnpj, phone, email) VALUES('FOCO', 0, 0, '');
INSERT INTO dbfiis.administration (name, cnpj, phone, email) VALUES('BANCO FATOR', 0, 0, '');