INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('BRL TRUST', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('AZ QUEST', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('RIO BRAVO', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('AF Invest Real Estate', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('EXES GESTORA DE RECURSOS', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('Autonomy Investimentos', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('CAPITANIA CAPITAL S.A.', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('BTG PACTUAL', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('Alianza Gestão de Recursos', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('ALIANZA GESTÃO', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('Bloxs Asset', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('SCAI', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('NAVI REAL ESTATE SELECTION', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('CARBYNE GESTÃO DE RECURSOS', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('QUELUZ', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('SONATA GESTÃO DE RECURSOS LTDA', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('OPEN KAPITAL GESTÃO', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('ARX Investimentos', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('ASA ASSET', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('GRAPHEN', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('HEDGE INVESTMENTS', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('AZ QUEST PANORAMA', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('VBI REAL ESTATE', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('CAIXA ECONOMICA FEDERAL', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('BB GESTAO DE RECURSOS', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('TIVIO CAPITAL', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('BRAM – Bradesco', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('Banestes DTVM', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('BRIO', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('INTER', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('VBI e Catuaí', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('BlueMacaw', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('Bluecap', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('BLUE ASSET', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('Argucia Capital Management', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('OLIVEIRA TRUST', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('BOCAINA CAPITAL GESTORA DE RECURSOS', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('BRASIL PLURAL', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('Bresco', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('GRAPHEN INVESTIMENTOS', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('BGR Asset', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('Fram Capital', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('BRZ INVESTIMENTOS', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('HGI CAPITAL', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('BARZEL PROPERTIES GESTORA DE RECURSOS LTDA', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('Cartesia Capital', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('Zion Gestão', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('CREDIT SUISSE', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('Colina Central Gestão de Recursos', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('CANUMA CAPITAL LTDA', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('SPARTA', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('RBR GESTÃO', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('CATUAÍ', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('CIX CAPITAL', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('CLAVE ALTERNATIVOS GESTORA', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('CAPITÂNIA S.A.', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('CAPITANIA CAPITAL', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('CAPITANIA INVESTIMENTOS', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('CAIXA E RIO BRAVO', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('RB CAPITAL', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('CAIXA ASSET', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('CY.CAPITAL', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('DEVANT ASSET', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('PLANNER', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('OPPORTUNITY DTVM', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('DAYCOVAL', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('PORTOFINO GESTÃO', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('DAYCOVAL ASSET', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('ECO GESTÃO DE ATIVOS', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('ENGEFORM GESTÃO DE RECURSOS', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('WNT', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('ANGRA PARTNERS', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('EUQUEROINVESTIR GESTÃO', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('ANGÁ', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('POLO CAPITAL', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('BV DTVM', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('VOTORANTIM ASSET', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('COINVALORES', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('HBC CONSULTORIA E GESTÃO', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('FATOR ORE ASSET', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('SANTA FÉ', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('FATOR ADMINISTRAÇÃO DE RECURSOS', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('BR-CAPITAL', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('FG/A GESTORA DE RECURSOS LTDA.', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('null', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('INFRA LTDA', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('VCM GESTAO DE CAPITAL LTDA', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('Faria Lima Capital Ltda', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('ZERO CINCO UM CAPITAL', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('MULTIPLICA CAPITAL', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('FRONTEIRA', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('Figtree Capital', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('GUARDIAN GESTORA', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('GALAPAGOS CAPITAL', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('ZAGROS CAPITAL', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('GENIAL GESTÃO', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('GLP', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('ICATU VANGUARDA', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('Greenwich Gestão de Recursos Ltda', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('GAZIT BRASIL ASSET', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('XP Vista', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('HECTARE CAPITAL', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('HIGH ASSET MANAGEMENT LTDA.', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('PATRIA INVESTIMENTOS', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('TRUSTEE DTVM', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('VÓRTX', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('HSI GESTORA DE ATIVOS FINANCEIROS', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('Hemisfério Sul Investimentos', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('BTG Pactual e HotelInvest', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('INVESTCOOP ASSET MANAGEMENT', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('INTER ASSET', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('SFI INVESTIMENTOS', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('INVISTA REAL ESTATE', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('BREI', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('RIZA', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('ITAÚ UNIBANCO', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('ID GESTORA E ADMISTRADORA', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('SEQUÓIA', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('EQUITAS Administração', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('IRIDIUM GESTÃO', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('INVISTA ASSET MANAGEMENT LTDA.', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('GENESIS CAPITAL', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('JULIUS BAER FAMILY OFFICE', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('JHSF CAPITAL LTDA.', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('JACARANDÁ CAPITAL E GESTÃO LTDA.', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('JGP GESTÃO DE CRÉDITO', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('JPP GESTÃO', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('SAFRA ASSET', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('OURO PRETO', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('KINEA', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('KILIMA', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('KIJANI GESTORA DE RECURSOS LTDA.', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('Legatus', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('LCP GESTORA DE RECURSOS LTDA', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('Lakewood Gestao de recursos', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('RIZA GESTORA DE RECURSOS', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('LEBLON EQUITIES', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('LESTE FINANCIAL SERVICES', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('MAUA CAPITAL REAL ESTATE', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('MANATÍ CAPITAL MANAGEMENT LTDA', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('MÉRITO INVESTIMENTOS', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('MOGNO CAPITAL', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('MINT CAPITAL', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('NEVES ASSET', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('NextCap Partners Asset', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('XP VISTA ', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('BRPP', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('NEX GESTÃO DE RECURSOS', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('TC CONSULTORIA E ADMINISTRAÇÃO LTDA', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('NU ASSET MANAGEMENT', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('VECTOR ADMINISTRAÇÃO DE RECURSOS FINANCEIROS LTDA', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('NIKOS GESTÃO DE RECURSOS', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('FATOR INNOVATION', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('CPV CAPITAL', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('MININVEST GESTORA DE RECURSOS', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('JPP GESTÃO E FATOR ORE', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('BRKB DTVM', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('PATAGÔNIA CAPITAL', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('EXANTE ASSET', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('Apolo Administração de Recursos', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('PLURAL GESTÃO DE RECURSOS', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('Paramis BR Investimentos', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('PANORAMA CAPITAL', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('PRISMA CAPITAL', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('ÓRAMA', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('MODAL', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('CVPAR', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('QUASAR ASSET MANAGEMENT', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('RBR Private Equity', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('JGP REAL ESTATE', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('REC', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('SINGULARE', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('CPV CAPITAL GESTÃO DE RECURSOS', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('REAL INVESTOR GESTÃO DE RECURSOS LTDA', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('REAG ASSET MANAGEMENT', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('Santander Brasil', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('BRB DTVM', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('CULTINVEST ASSET', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('BLUEWAVE ASSET', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('Suno Gestora de Recursos LTDA.', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('TAG INVESTIMENTOS', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('GENIAL INVESTIMENTOS', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('SPX SYN GESTAO DE RECURSOS LTDA.', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('R CAPITAL ASSET', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('STONEX INVESTIMENTOS', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('INTER DTVM', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('G5', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('TREECORP PARTNERS', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('Tellus Investimentos', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('TG Core Asset', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('UNITAS', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('Rio Bravo e Tellus', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('TRX', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('TISHMAN SPEYER', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('URCA GESTÃO', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('Vectis Gestão de Recursos', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('VINCI REAL ESTATE', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('Vera Cruz Asset Management', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('VOTORANTIM', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('VALORA GESTÃO', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('JULIUS BAER FAMILY OFFICE LTDA', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('VINCI INFRAESTRUTURA', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('QUELUZ GESTÃO', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('V2 INVESTIMENTOS', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('WHG', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('WARREN', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('XP GESTÃO', 0, 0, '');
INSERT INTO dbfiis.manager (name, cnpj, phone, email) VALUES('ZAVIT GESTÃO DE RECURSOS LTDA.', 0, 0, '');